package hello;

import hello.domain.Message;
import hello.repos.MessageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller // This means that this class is a Controller

public class GreetingController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MessageRepository msgRepository;

    @RequestMapping("/greeting") // This means URL's start with /demo (after Application path)
    public String greeting(@RequestParam(value = "name", required = false, defaultValue = "World") String name, Model model) {
        model.addAttribute("name", name);
        return "greeting";
    }

    @RequestMapping
    public String main(String name, Model model) {
        return "main";
    }

    @RequestMapping("/viewDB")
    public String viewDB(String name, Model model) {
        Iterable<Message> messages = msgRepository.findAll();
        model.addAttribute("messages", messages);
        return "viewDB";
    }
}
